edition = "2021"
newline_style = "Unix"
report_todo = "Always"
report_fixme = "Always"
max_width = 80
hard_tabs = false
tab_spaces = 4
wrap_comments = true
merge_imports = true
normalize_comments = true
merge_derives = true
